name: Group Dependabot PRs

on:
  schedule:
    # 毎週月曜日の午前3時に実行（UTCタイムゾーン）
    - cron: '0 3 * * 1'
  
  # 手動で実行することも可能
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-group:
    name: Group Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # このアクションは直接PRをグループ化できる別のアクションに置き換え
      - name: Group Dependabot PRs
        uses: dependabot/fetch-metadata@v1.6.0
        
      - name: Find Dependabot PRs
        id: find-prs
        run: |
          PR_NUMBERS=$(gh pr list --author "dependabot[bot]" --json number --jq '.[].number' | tr '\n' ' ')
          echo "pr_numbers=$PR_NUMBERS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Group and comment on Dependabot PRs
        if: steps.find-prs.outputs.pr_numbers != ''
        run: |
          for PR_NUMBER in ${{ steps.find-prs.outputs.pr_numbers }}; do
            gh pr comment "$PR_NUMBER" --body "Dependabot PRs will be grouped and merged automatically."
            gh pr merge --auto --squash "$PR_NUMBER"
            gh pr edit "$PR_NUMBER" --add-label "dependencies"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}